//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTODB_application3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENY_TOCHKI
    {
        public long TORGOVAJA_TOCHKA { get; set; }
        public long TOVAR { get; set; }
        public Nullable<long> CENA { get; set; }
    
        public virtual TORGOVAJA_TOCHKA TORGOVAJA_TOCHKA1 { get; set; }
        public virtual SPISOK_TOVAROV SPISOK_TOVAROV { get; set; }
    }
}
