//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTODB_application3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISTODB_connection : DbContext
    {
        public ISTODB_connection()
            : base("name=ISTODB_connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CENY_TOCHKI> CENY_TOCHKI { get; set; }
        public DbSet<NOMENKLTR_TCHK> NOMENKLTR_TCHK { get; set; }
        public DbSet<POKUPATELI> POKUPATELI { get; set; }
        public DbSet<PRODAVCY> PRODAVCY { get; set; }
        public DbSet<PRODAZHI> PRODAZHI { get; set; }
        public DbSet<SPISOK_TOVAROV> SPISOK_TOVAROV { get; set; }
        public DbSet<TORGOVAJA_TOCHKA> TORGOVAJA_TOCHKA { get; set; }
        public DbSet<UNIVERMAG> UNIVERMAG { get; set; }
    }
}
