//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTODB_application3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODAZHI
    {
        public PRODAZHI()
        {
            this.UNIVERMAG = new HashSet<UNIVERMAG>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PRODAVEC { get; set; }
        public Nullable<long> POKUPATEL { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<long> TOVAR { get; set; }
        public Nullable<int> KOLICHESTVO { get; set; }
    
        public virtual POKUPATELI POKUPATELI { get; set; }
        public virtual PRODAVCY PRODAVCY { get; set; }
        public virtual SPISOK_TOVAROV SPISOK_TOVAROV { get; set; }
        public virtual ICollection<UNIVERMAG> UNIVERMAG { get; set; }
    }
}
