//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTODB_application3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODAVCY
    {
        public PRODAVCY()
        {
            this.PRODAZHI = new HashSet<PRODAZHI>();
        }
    
        public long ID { get; set; }
        public string IMJA_PRODAVCA { get; set; }
        public Nullable<long> ZARPLATA { get; set; }
    
        public virtual ICollection<PRODAZHI> PRODAZHI { get; set; }
    }
}
