//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTODB_application3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIVERMAG
    {
        public long ID { get; set; }
        public Nullable<long> RAZMER_TORG_TCHK { get; set; }
        public Nullable<int> CHISLO_PRILAVKOV { get; set; }
        public long PRODAZHI { get; set; }
    
        public virtual PRODAZHI PRODAZHI1 { get; set; }
        public virtual TORGOVAJA_TOCHKA TORGOVAJA_TOCHKA { get; set; }
    }
}
